//CONST USER
export const AUTHETICATE_USER = 'AUTHETICATE_USER';
export const CREATE_USER = 'CREATE_USER'
export const LOAD_USER = 'LOAD_USER'
export const SUCCESS_USER = 'SUCCESS_USER'
export const ERROR_USER = 'ERROR_USER'

// CONST ANIMAL
export const FETCH_ANIMALS = 'FETCH_ANIMALS'
export const CREATE_ANIMAL = 'CREATE_ANIMAL'
export const SUCESS_ANIMALS = 'SUCESS_ANIMALS'
export const LOAD_ANIMALS  = 'LOAD_ANIMALS'
export const ERROR_ANIMALS  = 'ERROR_ANIMALS'

//CONST PESSOAS
export const CREATE_PESSOA = 'CREATE_PESSOA'
export const SUCESS_PESSOA = 'SUCESS_PESSOA'
export const LOAD_PESSOA = 'LOAD_PESSOA'
export const ERROR_PESSOA  = 'ERROR_PESSOA'
export const EXIT_PESSOA  = 'EXIT_PESSOA'

//CONST PRONTUARIOS
export const CREATE_PRONTUARIO = 'CREATE_PRONTUARIO'
export const SUCESS_PRONTUARIO = 'SUCESS_PRONTUARIO'
export const LOAD_PRONTUARIO = 'LOAD_PRONTUARIO'
export const ERROR_PRONTUARIO  = 'ERROR_PRONTUARIO'

//CONST TRATAMENTOS
export const CREATE_TRATAMENTOS = 'CREATE_TRATAMENTOS'
export const SUCESS_TRATAMENTOS = 'SUCESS_TRATAMENTOS'
export const LOAD_TRATAMENTOS = 'LOAD_TRATAMENTOS'
export const ERROR_TRATAMENTOS  = 'ERROR_TRATAMENTOS'

//CONST VACINAS
export const CREATE_VACINAS = 'CREATE_VACINAS'
export const SUCESS_VACINAS = 'SUCESS_VACINAS'
export const LOAD_VACINAS = 'LOAD_VACINAS'
export const ERROR_VACINAS  = 'ERROR_VACINAS'

//CONST MEDICAMENTOS
export const CREATE_MEDICAMENTOS = 'CREATE_MEDICAMENTOS'
export const SUCESS_MEDICAMENTOS = 'SUCESS_MEDICAMENTOS'
export const LOAD_MEDICAMENTOS = 'LOAD_MEDICAMENTOS'
export const ERROR_MEDICAMENTOS  = 'ERROR_MEDICAMENTOS'